import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { stringify } from 'yaml';
import type { PlannerBrain } from './llm/brain.js';
import type { GeneratedTest } from './llm/schemas.js';
import type { PageLike } from './runner/actions.js';
import { defaultSnapshot } from './runner/executor.js';
import { TESTS_RELATIVE_DIR, type TestFile } from './runner/testfile.js';
import { fsReason } from './report/errors.js';

export class PlannerError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'PlannerError';
  }
}

/** A generated test plus the route coverage the planner assigns to it (design D6). */
export type TestDraft = GeneratedTest & { routes: string[] };

export interface GenerateOptions {
  route: string;
  baseUrl: string;
  /** Changed files that mapped to this route; empty for `--route` generation. */
  changedFiles: string[];
  brain: PlannerBrain;
  /**
   * Required, not optional: `plan` authenticates and then browses the session, so
   * a page can render the credential. This command shipped with no masking at all
   * because the boundary was closed at one call site instead of being defined over
   * every caller that prompts a model (design D2).
   */
  mask: (text: string) => string;
  /** Injectable snapshotter (defaults to live ariaSnapshot), mirroring the executor. */
  snapshot?: (page: PageLike) => Promise<string>;
  /**
   * Caps accessibility-tree lines sent to the model (mirrors the executor's
   * option of the same name). Only applies to the default snapshotter; an
   * injected `snapshot` fully replaces it.
   */
  maxSnapshotLines?: number;
  /**
   * The configured `browser.timeout_ms` (design D1, browser-patience): bounds how
   * long the route's initial load waits, mirroring the executor's `navigate`
   * action.
   *
   * Required, not optional — same reasoning as `ExecutorOptions.timeoutMs`
   * (runner/executor.ts): the one real caller (`plan`) always has the configured
   * value on hand, and an unset value has no legitimate "don't care" meaning here
   * — it would silently reinstate the fixed 30s this change exists to make
   * configurable.
   */
  timeoutMs: number;
}

/** Steps naming a credential alongside a quoted literal, with no `{{env.*}}` placeholder. */
const CREDENTIAL_WORD = /\b(password|passwd|api[ _-]?key|token|secret|credential)\b/i;
const QUOTED_LITERAL = /["'][^"']+["']/;

/**
 * Returns the steps that appear to carry a literal secret instead of a placeholder
 * (design D8). A credential word alone is not enough — "check the password field is
 * visible" is fine; it is the quoted literal without `{{env.*}}` that is a violation.
 */
export function findSecretLiterals(steps: string[]): string[] {
  return steps.filter(
    (step) => CREDENTIAL_WORD.test(step) && QUOTED_LITERAL.test(step) && !step.includes('{{env.'),
  );
}

/**
 * Derives the test filename stem from a route: `/` → `home`, everything else
 * lowercased with non-alphanumerics collapsed to `-` (design D7).
 */
export function routeToSlug(route: string): string {
  const slug = route
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
  return slug || 'home';
}

export interface ProvenanceMeta {
  route: string;
  /** Base ref the diff came from; omitted when the route was named with `--route`. */
  base?: string;
  /** ISO date (YYYY-MM-DD); injectable so tests are not clock-dependent. */
  date?: string;
}

/** Renders a draft as YAML with the provenance comment header (design D7). */
export function renderTestYaml(draft: TestDraft, meta: ProvenanceMeta): string {
  const header = [
    '# Generated by `blastproof plan` — review before committing.',
    `# route: ${meta.route}`,
    `# base: ${meta.base ?? '(explicit --route)'}`,
    `# generated: ${meta.date ?? new Date().toISOString().slice(0, 10)}`,
    '',
  ].join('\n');
  return (
    header +
    stringify({
      summary: draft.summary,
      priority: draft.priority,
      tags: draft.tags,
      routes: draft.routes,
      steps: draft.steps,
    })
  );
}

/**
 * Generates one test draft for a route: load it, snapshot it, one LLM call (design D2/D4).
 * `routes` is set here, never taken from the model, so the draft provably closes the
 * coverage gap that triggered it (design D6).
 */
export async function generateForRoute(page: PageLike, options: GenerateOptions): Promise<TestDraft> {
  const { route, baseUrl, changedFiles, brain, mask, snapshot, maxSnapshotLines, timeoutMs } = options;
  const takeSnapshot = snapshot ?? ((p: PageLike) => defaultSnapshot(p, maxSnapshotLines));

  const url = new URL(route, baseUrl).toString();
  try {
    // Same knob as the executor's `navigate` action (design D1): a slow app is
    // waited for at the configured timeout, not a value fixed in the code.
    await page.goto(url, { timeout: timeoutMs });
  } catch (error) {
    throw new PlannerError(
      `Cannot load ${url}: ${error instanceof Error ? error.message : String(error)}`,
    );
  }

  const generated = await brain.planTest({
    route,
    snapshot: mask(await takeSnapshot(page)),
    changedFiles,
  });

  const leaked = findSecretLiterals(generated.steps);
  if (leaked.length > 0) {
    throw new PlannerError(
      `Generated steps contain literal secrets instead of {{env.VAR}} placeholders: ${leaked.join(' | ')}`,
    );
  }

  return { ...generated, routes: [route] };
}

/**
 * Writes a draft under `.blastproof/tests/`, never overwriting: an existing target
 * fails this route with the conflicting path (design D7). Returns the path written.
 */
export async function writeDraft(
  cwd: string,
  draft: TestDraft,
  meta: ProvenanceMeta,
): Promise<string> {
  const dir = path.join(cwd, TESTS_RELATIVE_DIR);
  const file = path.join(dir, `${routeToSlug(meta.route)}.yaml`);
  try {
    await mkdir(dir, { recursive: true });
    // 'wx' fails if the file exists — atomic, so a concurrent write cannot slip through.
    await writeFile(file, renderTestYaml(draft, meta), { flag: 'wx' });
  } catch (error) {
    const err = error as NodeJS.ErrnoException;
    if (err.code === 'EEXIST' && err.syscall !== 'mkdir') {
      throw new PlannerError(
        `Refusing to overwrite ${path.relative(cwd, file)} (route ${meta.route}). ` +
          'Delete or rename it to regenerate.',
      );
    }
    throw new PlannerError(
      `Cannot write draft to ${file}: ${fsReason(error)}. Check that ${path.dirname(file)} is a directory you can write to, not a file.`
    );
  }
  return file;
}

/** Routes already covered by at least one test in the suite. */
export function coveredRoutes(tests: TestFile[]): Set<string> {
  return new Set(tests.flatMap((test) => test.routes));
}
